#! /bin/sh
#       Licensed to the Apache Software Foundation (ASF) under one
#       or more contributor license agreements.  See the NOTICE file
#       distributed with this work for additional information
#       regarding copyright ownership.  The ASF licenses this file
#       to you under the Apache License, Version 2.0 (the
#       "License"); you may not use this file except in compliance
#       with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing,
#       software distributed under the License is distributed on an
#       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#       KIND, either express or implied.  See the License for the
#       specific language governing permissions and limitations
#       under the License.

ANT=$(which ant)

if [ -z "$1" ]
then
  echo 'usage: debug <platform>'
  echo 'where <platform> can be one of "blackberry" or "playbook"'
  echo 'NOTE: please customize the project.properties file first before using this command!'
  exit 0
fi

if [ "$1" == "blackberry" ]
then
  echo 'Do you have a BlackBerry smartphone connected to your computer? (y/n)'
  read DEVICE
  if [ $DEVICE == "y" ]
  then
    $ANT blackberry debug-device
  else
    $ANT blackberry load-simulator
  fi
else
  if [ "$1" == "playbook" ]
  then
    echo 'Do you have a BlackBerry Playbook connected to your computer? (y/n)'
    read DEVICE
    if [ $DEVICE == "y" ]
    then
      $ANT playbook debug-device
    else
      $ANT playbook load-simulator
    fi
  else
    echo 'Platform not recognized! Please use one of "blackberry" or "playbook" for the platform parameter.'
  fi
fi
