#! /bin/sh
#       Licensed to the Apache Software Foundation (ASF) under one
#       or more contributor license agreements.  See the NOTICE file
#       distributed with this work for additional information
#       regarding copyright ownership.  The ASF licenses this file
#       to you under the Apache License, Version 2.0 (the
#       "License"); you may not use this file except in compliance
#       with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing,
#       software distributed under the License is distributed on an
#       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#       KIND, either express or implied.  See the License for the
#       specific language governing permissions and limitations
#       under the License.

ANT=$(which ant)

if [ -z "$1" ]
then
  echo 'usage: run <platform>'
  echo 'where <platform> can be one of "blackberry", "playbook" or "qnx"'
  echo 'NOTE: please customize the project.properties file first before using this command!'
  exit 0
fi

if [ "$1" == "blackberry" -o "$1" == "playbook" -o "$1" == "qnx" ]
then
  echo 'Do you have a BlackBerry device connected to your computer? (y/n)'
  read DEVICE
  if [ $DEVICE == "y" ]
  then
    $ANT $1 debug-device
  else
    $ANT $1 load-simulator
  fi
else
  echo 'Platform not recognized! Please use one of "blackberry", "playbook", or "qnx" for the platform parameter.'
fi
